### ISSUE TITLE
Not really a bug

### ISSUE THREAD

**Issue by jeslin** [radlib/radlib-cordova#29]
Just wanted to place this somewhere:

Once you have direct connected to something and either parse or stream, you can't do the other. Which makes sense because you shouldn't be able to do both, but we wanted to note this regardless.

**Comment by vinchan** [comment]
It won't be an issue at all because if you remember, we're integrating them together. We're no longer having the option to receive a stream. Instead, everytime we parse a "frame", we will send the frame back as part of the object field. So in a sense, connecting will give them the frame/stream whether they want it or not.

**Comment by vinchan** [comment]
Stream is removed. Frame is now being sent whenever parse is called.
